import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#07121d',
  },
  shell: {
    flex: 1,
  },
  shellHeader: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 12,
    padding: 24,
    paddingBottom: 12,
  },
  screenWrap: {
    flex: 1,
  },
  screenContent: {
    paddingHorizontal: 24,
    paddingBottom: 24,
    gap: 16,
  },
  connectionContent: {
    padding: 24,
    gap: 16,
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    padding: 24,
  },
  loadingText: {
    color: '#d5e3ee',
    fontSize: 15,
  },
  hero: {
    borderRadius: 28,
    padding: 24,
    backgroundColor: '#102338',
    borderWidth: 1,
    borderColor: '#1f3c56',
  },
  heroCompact: {
    flex: 1,
    borderRadius: 28,
    padding: 20,
    backgroundColor: '#102338',
    borderWidth: 1,
    borderColor: '#1f3c56',
  },
  kicker: {
    color: '#86d5ff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  title: {
    marginTop: 12,
    color: '#f3f8fc',
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 36,
  },
  subtitle: {
    marginTop: 10,
    color: '#a8bccd',
    fontSize: 15,
    lineHeight: 22,
  },
  shellTitle: {
    marginTop: 10,
    color: '#f3f8fc',
    fontSize: 22,
    fontWeight: '700',
  },
  shellSubtitle: {
    marginTop: 6,
    color: '#a8bccd',
    fontSize: 13,
    lineHeight: 20,
  },
  refreshButton: {
    minWidth: 88,
    borderRadius: 20,
    backgroundColor: '#16324b',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  refreshButtonText: {
    color: '#dce9f4',
    fontSize: 14,
    fontWeight: '700',
  },
  card: {
    borderRadius: 24,
    padding: 20,
    backgroundColor: '#0d1d2c',
    borderWidth: 1,
    borderColor: '#1d3347',
  },
  cardTitle: {
    color: '#f3f8fc',
    fontSize: 18,
    fontWeight: '600',
  },
  cardDescription: {
    marginTop: 6,
    marginBottom: 10,
    color: '#8ea5b8',
    fontSize: 13,
    lineHeight: 19,
  },
  fieldLabel: {
    marginTop: 6,
    marginBottom: 8,
    color: '#9db1c2',
    fontSize: 13,
    fontWeight: '600',
  },
  input: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#27445c',
    backgroundColor: '#091723',
    color: '#f3f8fc',
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  segment: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#27445c',
    backgroundColor: '#091723',
    paddingVertical: 12,
    alignItems: 'center',
  },
  segmentActive: {
    backgroundColor: '#14314b',
    borderColor: '#4fbef7',
  },
  segmentText: {
    color: '#9db1c2',
    fontSize: 14,
    fontWeight: '600',
  },
  segmentTextActive: {
    color: '#f3f8fc',
  },
  primaryButton: {
    marginTop: 18,
    borderRadius: 18,
    backgroundColor: '#2188c9',
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#f3f8fc',
    fontSize: 15,
    fontWeight: '700',
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  secondaryButton: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: '#16324b',
    paddingVertical: 14,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#dce9f4',
    fontSize: 14,
    fontWeight: '600',
  },
  ghostButton: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#2b4458',
    paddingVertical: 14,
    alignItems: 'center',
  },
  ghostButtonText: {
    color: '#c0d1de',
    fontSize: 14,
    fontWeight: '600',
  },
  errorText: {
    marginTop: 12,
    color: '#ff8c91',
    fontSize: 14,
    lineHeight: 21,
  },
  summaryGrid: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  summaryGridCompact: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  rowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryBlock: {
    flex: 1,
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#091723',
    borderWidth: 1,
    borderColor: '#20384d',
  },
  summaryValue: {
    color: '#f3f8fc',
    fontSize: 30,
    fontWeight: '700',
  },
  summaryLabel: {
    marginTop: 6,
    color: '#92a9bb',
    fontSize: 13,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  emptyText: {
    color: '#d5e3ee',
    fontSize: 15,
    lineHeight: 24,
  },
  serverCard: {
    borderRadius: 20,
    padding: 16,
    backgroundColor: '#091723',
    borderWidth: 1,
    borderColor: '#20384d',
    marginTop: 12,
  },
  serverHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  serverTitle: {
    flex: 1,
    color: '#f3f8fc',
    fontSize: 17,
    fontWeight: '700',
  },
  serverMeta: {
    marginTop: 10,
    color: '#8ea5b8',
    fontSize: 12,
    lineHeight: 18,
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusOnline: {
    backgroundColor: '#173925',
  },
  statusOffline: {
    backgroundColor: '#3a1b24',
  },
  statusBadgeText: {
    color: '#f3f8fc',
    fontSize: 12,
    fontWeight: '700',
  },
  metricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  metricItem: {
    color: '#d5e3ee',
    fontSize: 13,
    backgroundColor: '#102638',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  eventRow: {
    borderTopWidth: 1,
    borderTopColor: '#1b3042',
    paddingTop: 12,
    marginTop: 12,
  },
  eventTitle: {
    color: '#edf5fb',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    flex: 1,
  },
  eventMeta: {
    marginTop: 6,
    color: '#8ea5b8',
    fontSize: 12,
    lineHeight: 18,
  },
  preferenceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#1b3042',
  },
  preferenceStack: {
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#1b3042',
    gap: 10,
  },
  preferenceCopy: {
    flex: 1,
    gap: 4,
  },
  preferenceTitle: {
    color: '#edf5fb',
    fontSize: 14,
    fontWeight: '600',
  },
  preferenceBody: {
    color: '#8ea5b8',
    fontSize: 12,
    lineHeight: 18,
  },
  preferenceValue: {
    color: '#86d5ff',
    fontSize: 13,
    fontWeight: '700',
  },
  subscriptionWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  subscriptionChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#29445b',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#091723',
  },
  subscriptionChipActive: {
    borderColor: '#4fbef7',
    backgroundColor: '#14314b',
  },
  subscriptionChipText: {
    color: '#b7cad8',
    fontSize: 12,
    fontWeight: '600',
  },
  subscriptionChipTextActive: {
    color: '#f3f8fc',
  },
  bottomTabs: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: '#162637',
    backgroundColor: '#07121d',
  },
  bottomTab: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: '#0d1d2c',
    borderWidth: 1,
    borderColor: '#1d3347',
  },
  bottomTabActive: {
    backgroundColor: '#14314b',
    borderColor: '#4fbef7',
  },
  bottomTabText: {
    color: '#9db1c2',
    fontSize: 13,
    fontWeight: '700',
  },
  bottomTabTextActive: {
    color: '#f3f8fc',
  },
  inlineActionButton: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#16324b',
  },
  inlineActionButtonText: {
    color: '#dce9f4',
    fontSize: 12,
    fontWeight: '700',
  },
  secondaryButtonWide: {
    marginTop: 16,
    borderRadius: 16,
    backgroundColor: '#16324b',
    paddingVertical: 14,
    alignItems: 'center',
  },
  ghostButtonWide: {
    marginTop: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#2b4458',
    paddingVertical: 14,
    alignItems: 'center',
  },
  connectionMeta: {
    marginTop: 10,
    color: '#d5e3ee',
    fontSize: 14,
    lineHeight: 20,
  },
});